name: iab-latest
channels:
  - etetoolkit
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - backcall=0.1.0
  - bzip2=1.0.6
  - ca-certificates=2018.4.16
  - cachecontrol=0.12.5
  - certifi=2018.4.16
  - cffi=1.11.5
  - chardet=3.0.4
  - contextlib2=0.5.5
  - cryptography=2.3
  - cryptography-vectors=2.3
  - cycler=0.10.0
  - dbus=1.13.0
  - decorator=4.3.0
  - expat=2.2.5
  - fontconfig=2.13.0
  - freetype=2.8.1
  - future=0.16.0
  - gettext=0.19.8.1
  - glib=2.55.0
  - gst-plugins-base=1.12.5
  - gstreamer=1.12.5
  - icu=58.2
  - idna=2.7
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - jedi=0.12.1
  - jpeg=9c
  - kiwisolver=1.0.1
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.34
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lockfile=0.12.2
  - lxml=4.2.4
  - matplotlib=2.2.2
  - msgpack-python=0.5.6
  - natsort=5.3.3
  - ncurses=6.1
  - nose=1.3.7
  - openssl=1.0.2o
  - pandas=0.17.1
  - parso=0.3.1
  - pcre=8.41
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pip=18.0
  - prompt_toolkit=1.0.15
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - pysocks=1.6.8
  - python=3.5.5
  - python-dateutil=2.7.3
  - pytz=2018.5
  - qt=5.6.2
  - readline=7.0
  - requests=2.19.1
  - scikit-bio=0.4.2
  - setuptools=40.0.0
  - simplegeneric=0.8.1
  - sip=4.18
  - six=1.11.0
  - sqlite=3.24.0
  - tk=8.6.8
  - tornado=5.1
  - traitlets=4.3.2
  - urllib3=1.23
  - wcwidth=0.1.7
  - wheel=0.31.1
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xz=5.2.4
  - zlib=1.2.11
  - bz2file=0.98
  - libgcc-ng=7.2.0
  - libgfortran=3.0.0
  - libstdcxx-ng=7.2.0
  - mkl=11.3.3
  - numpy=1.10.4
  - scipy=0.17.1
  - ete3=3.1.1

